export { LocalConnection } from "./local-connection.js";
export { SerialConnection } from "./serial-connection.js";
export type { SerialConfig } from "./serial-connection.js";
export { AdbConnection } from "./adb-connection.js";
export { FastbootConnection } from "./fastboot-connection.js";
export { OutputPipe } from "./output-pipe.js";
export { RingBuffer } from "./ring-buffer.js";
export { RuleDetector } from "./rule-detector.js";
export type { Rule, RuleKind, RuleSeverity } from "./rule-detector.js";
export { Aggregator } from "./aggregator.js";
export { ConnectionManager } from "./connection-manager.js";
export type { TransportType } from "./connection-manager.js";
export { TargetManager } from "./target-manager.js";
export { FakeConnection } from "./fake-connection.js";
