export type { Connection, ExecResult } from "./connection.js";
export { LocalConnection } from "./local.js";
export { SerialConnection } from "./serial.js";
export type { SerialConfig } from "./serial.js";
export { AdbConnection } from "./adb.js";
export { FastbootConnection } from "./fastboot.js";
export { FakeConnection } from "./fake.js";
export { OutputPipe } from "./output-pipe.js";
export { RingBuffer } from "./ring-buffer.js";
export { RuleDetector } from "./rule-detector.js";
export type { Rule, RuleSeverity } from "./rule-detector.js";
export { Aggregator } from "./aggregator.js";
export { ConnectionManager } from "./connection-manager.js";
export type { Transport } from "./connection-manager.js";
export { TargetManager } from "./target-manager.js";
