export type { Connection, ExecResult } from "./connection.js";
export { LocalConnection } from "./local.js";
export { SerialConnection, createRealSerialPort } from "./serial.js";
export type { SerialConfig, SerialPortLike, SerialPortFactory } from "./serial.js";
export { AdbConnection } from "./adb.js";
export { RealAdbClient, AdbError, classifyAdbError, adbErrorHint } from "./adb-client.js";
export type { AdbClient, AdbExecResult, AdbDeviceState } from "./adb-client.js";
export { FakeAdbClient } from "./fake-adb-client.js";
export type { FakeAdbRule } from "./fake-adb-client.js";
export { FastbootConnection } from "./fastboot.js";
export { Ssh2Connection } from "./ssh.js";
export type { SshClientLike } from "./ssh.js";
export { FakeSshClient } from "./fake-ssh.js";
export type { SshConnectionConfig, SshRuntimeState, HostKeyPolicy, SshCommandPolicy } from "./ssh-config.js";
export { FakeConnection } from "./fake.js";
export { OutputPipe } from "./output-pipe.js";
export { RingBuffer } from "./ring-buffer.js";
export { RuleDetector } from "./rule-detector.js";
export type { Rule, RuleSeverity } from "./rule-detector.js";
export { Aggregator } from "./aggregator.js";
export { ConnectionManager } from "./connection-manager.js";
export type { Transport } from "./connection-manager.js";
export { TargetManager } from "./target-manager.js";
